Repository googleapis/python-secret-manager, pull requests merged in 2021-04, with the labels that each got.

#98 chore: add tarfile
  secretmanager-v1beta1-py.tar.gz
  synth.metadata
Labels: api: secretmanager, cla: yes, context: none

#101 chore: add license headers
  .pre-commit-config.yaml
  docs/conf.py
  secretmanager-v1beta1-py.tar.gz
  synth.metadata
Labels: api: secretmanager, cla: yes, context: partial

#104 chore: prevent normalization of semver versioning
  setup.py
Labels: api: secretmanager, cla: yes

#107 chore: update testing - ignore files, add constraints
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  renovate.json
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: secretmanager, cla: yes, context: full

#105 chore(revert): revert preventing normalization
  setup.py
Labels: api: secretmanager, automerge, cla: yes
