Repository googleapis/python-secret-manager, pull requests merged in 2021-08, with the labels that each got.

#173 chore: require CODEOWNER review and up to date branches
  .github/sync-repo-settings.yaml
Labels: api: secretmanager, automerge, cla: yes

#178 chore: clean up secrets created by sample tests
  samples/snippets/snippets_test.py
Labels: api: secretmanager, cla: yes, samples

#187 chore: migrate default branch from master to main
  .github/sync-repo-settings.yaml
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  docs/conf.py
  owlbot.py
Labels: api: secretmanager, cla: yes
